import trimesh
l0 = trimesh.load('./base_link.stl')
l0.show()
l1 = trimesh.load('./link1.stl')
l1.show()
l2 = trimesh.load('link2.stl')
l2.show()
l3 = trimesh.load('link3.stl')
l3.show()
l4 = trimesh.load('link4.stl')
l4.show()
l5 = trimesh.load('link5.stl')
l5.show()
l6 = trimesh.load('link6.stl')
l6.show()
